import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {
  return (
    <>
        <Head>
          <title>Corresponsabilidad Social</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <h1>Hola!!</h1>        
    </>
  )
}
